fix(tocco-ui): stack menu items horizontally
error:    ItemMenu and ItemAccordion in MenuStack are layout out horizontally.
solution: Use flexbox properties to layout vertically.
reason:   Error was introduced by change d7f3c8ab3.